colors.draw_bold_text_with_bright_colors = true

# Colors (Tokyo Night)
# Source https//github.com/zatchheems/tokyo-night-alacritty-theme

# Default colors
[colors.primary]
background = '#1a1b26'
foreground = '#a9b1d6'

# Normal colors
[colors.normal]
black   = '#32344a'
red     = '#f7768e'
green   = '#9ece6a'
yellow  = '#e0af68'
blue    = '#7aa2f7'
magenta = '#ad8ee6'
cyan    = '#449dab'
white   = '#787c99'

# Bright colors
[colors.bright]
black   = '#444b6a'
red     = '#ff7a93'
green   = '#b9f27c'
yellow  = '#ff9e64'
blue    = '#7da6ff'
magenta = '#bb9af7'
cyan    = '#0db9d7'
white   = '#acb0d0'


[font]
size = 12

[font.bold]
family = "Fira Code"
style = "Bold"

[font.bold_italic]
family = "Fira Code"
style = "Bold Italic"

[font.italic]
family = "Fira Code"
style = "Italic"

[font.normal]
family = "Fira Code"
style = "Medium"

[window.padding]
x = 15
y = 15


[scrolling]
history = 100000
multiplier = 15

[cursor]
style = { shape = "Beam", blinking = "Always" }


[selection]
save_to_clipboard = true


[general]
live_config_reload = true
